server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: ${SPRING_KAFKA_LISTENER_AUTO_STARTUP:true}

groq:
  api-key: ${GROQ_API_KEY}
  url: ${GROQ_URL}

app:
  kafka-enabled: ${KAFKA_ENABLED:false}
